spring:
  profiles: dev
  datasource:
    url: jdbc:h2:file:C:/DEV/DB/cargo-funcionalidade.txt;CIPHER=AES
    username: sj-acesso
    password: sj-acesso
  jpa:
    show-sql: true
    hibernate:      ddl-auto: update
logging:
  level:
    sql: debug
---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:cargo-funcionalidade
    username: sj-acesso
    password: filepwd sj-acesso
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  mail:    host: smtp.gmail.com
    port: 587
    username: example@gmail.com
    password: pass-example
    properties:      mail:
        smtp:
          starttsl:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    
logging:
  level:
    sql: debug

---
spring:
  profiles: prod
  datasource:
    url: jdbc:h2:file:/etc/cargo-funcionalidade.txt;CIPHER=AES
    username: sj-acesso
    password: sj-acesso
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
logging:
  level:
    sql: warn
